#!/bin/bash
#
# Created by 弱弱的胖橘猫丷
#

if [ ! -d dtbs ];
then
    mkdir -p dtbs
fi

make_dtbs() {
  for dts_sources in boot-dts/*.dts
    do
      ./dtc_binary -I dts -O dtb -o $dts_sources.dtb $dts_sources
  done
}

move_dtbs() {
  for dtb_sources in boot-dts/*.dtb
    do
      mv $dtb_sources dtbs/
  done
}

append_dtb() {
  for file_source in dtbs/*.dtb
    do
      cat $file_source >> uefi_image
  done 
}

  while [ $# != 0 ]; do
      $1
      shift;
  done

