#!/bin/bash
#
# Created by 弱弱的胖橘猫丷
#

make_dtbs() {
  for dts_sources in dts/*.dts
    do
      ./dtc_binary -I dts -O dtb -o $dts_sources.dtb $dts_sources
  done
}

append_dtb() {
  for file_source in dtbs/*.dtb
    do
      cat $file_source >> uefi_image
  done 
}

  while [ $# != 0 ]; do
      $1
      shift;
  done

