.PHONY: clean

clean:
	@find . -maxdepth 1 -type d -name "Build" -exec rm -r -f {} \;
	@find . -maxdepth 1 -type f -name "*.dtb" -exec rm -r -f {} \;
	@find . -maxdepth 1 -type l -name "HOSTDTC" -exec rm -r -f {} \;

